### ISSUE TITLE
Unable to favorite any Living Atlas item as an organization administrator using shareItemWithGroup

### ISSUE THREAD

**Issue by aravindesri** [Esri/arcgis-rest-js#882] opened 2021-07-28 19:18 UTC
### Issue description
I, as an org admin, am unable to favorite a Living Atlas item (Owned by a user outside of my organization) to my favorite's group.

### Context
Since https://github.com/Esri/arcgis-rest-js/commit/e8ab1bc3ad4498e5c1ac19fc0f1c24013de0a8df, the `shareItemWithGroup` now handles a different API route to share an item to a group if the sharing was performed by an org_admin. This route uses the `/content/users/:ownername/items/:itemid/share` which when favoriting a Living Atlas item, does not have the right permissions to add to favorite group since the item and the user don't belong to the same organization as the org admin and therefore no item control.

### Steps to reproduce
1. Use the following inputs to run the shareItemWithGroup function: 
    A. id: bf7c462f912f4d41ba262ba3c0e9008f
    B. groupId: "Org admin favorite group ID"
    C. owner: "cfrye_UO"
    D. authentication: Org admin user session

### Seen behavior
I get an error that I do not have permissions to favorite the item.

### Expected behavior
I would expect that an admin is able to favorite a Living Atlas item just like any other member of the organization.

### Version
Browser: Chrome, Firefox, Safari (all OS)
ArcGIS-Rest-Js: v3.2.0

### Use case
The ArcGIS StoryMaps app offers several item browser views in its ecosystem. There's a browser to explore and search for Living Atlas web maps, scenes, storymaps, apps and files. This browser view can be accessed by both an admin and any non-admin user. 
<img width="1400" alt="Screen Shot 2021-07-28 at 12 15 59 PM" src="https://user-images.githubusercontent.com/17153133/127382488-21cc7d6a-a9ad-4446-8e4a-a2c158ab4db8.png">

We're running into this issue specifically for the org_admin use case.

**Comment by patrickarlt** [comment] 2021-09-14 22:59
@dbouwman @tomwayson can you take a look?

**Comment by dbouwman** [comment] 2021-09-21 14:13
Addressed by #919

**Comment by tonybattsesri** [comment] 2022-08-18 22:43
We are currently having what seems to be the same issue, only occuring in our lower environments that are using `"@esri/arcgis-rest-portal": "^4.0.0"`

We're getting the error message: `You do not have permissions to access this resource or perform this operation` when calling shareItemWithGroup() as a user that does not own the item they are trying to favorite.

In staging the share request is hitting this end point:
https://www.arcgis.com/sharing/rest/content/users/sharon@storymaps.com/items/b42adba2417d4c1c96ff31e52a4f9650/share

In production where we are using this version: `"@esri/arcgis-rest-portal": "^3.4.3"`
The share request is hitting the below endpoint and this is working properly: 
https://www.arcgis.com/sharing/rest/content/items/b42adba2417d4c1c96ff31e52a4f9650/share

**Comment by dbouwman** [comment] 2022-08-19 17:48
@tonybattsesri  - We have confirmed that there is an issue that's connected to situations involving sharing an item to a group across org's, which is further compounded with org_admin users.

We are investigating how resolve this "correctly" without breaking other needed behaviors.

**Comment by dbouwman** [comment] 2022-08-22 21:15
This was addressed for `4.x` by PR #1011, which was released with `4.0.4` of `@esri/arcgis-rest-portal`

**Closed by dbouwman** 2022-08-22 21:15 UTC
