### ISSUE TITLE
Should handle empty responses (e.g., CORS errors)

### ISSUE THREAD

**Issue by mvdbster** [Esri/arcgis-rest-js#579] opened 2019-06-06 09:12 UTC
Some ArcGIS REST requests fail without a response object, for example, when a CORS error occurs.

In this case, `arcgis-rest-js` seems to throw an error with the string `"TypeError: Failed to fetch"` instead of the usual error object (see screenshot). This makes it difficult to handle those errors.

Would it be possible to handle these more gracefully?

<img width="902" alt="Screen Shot 2019-06-06 at 11 01 49" src="https://user-images.githubusercontent.com/19687652/59021335-e6589300-884b-11e9-9a94-a4aba4c0fd43.png">

**Comment by patrickarlt** [comment] 2019-07-03 00:16
As awesome as it might be to detect this this is actually the intended behavior of the spec. See these StackOverflow answers for a little more detail:

* https://stackoverflow.com/a/19325710
* https://stackoverflow.com/a/6734427

basically you cant distinguish between CORS errors and regular network errors because if you COULD then you could maliciously use the failed CORS errors to learn thing about the endpoint you are attacking, like the fact that you can't use CORS or other things.

Chrome and Firefox both add their own "pretty" error messages which are what you see above and in  these cases:

![Screenshot 2019-07-02 16 59 44](https://user-images.githubusercontent.com/378557/60554044-eb91ec00-9cea-11e9-89d6-c104f2b35f3b.png)
![Screenshot 2019-07-02 16 58 51](https://user-images.githubusercontent.com/378557/60554045-eb91ec00-9cea-11e9-9626-5479e3db917e.png)

But our application code only ever sees a `TypeError`. To try this out paste the following in any DevTools console:

```js
fetch("https://sampleserver3.arcgisonline.com/ArcGIS/rest/services/?f=json&pretty=true")
  .then(r => {
    console.log("Response");
    debugger;
  })
  .catch(e => {
    console.log("Error");
    debugger;
  })
```

We don't attach a `.catch()` handler inside `request` by default right now.

The only potential solution would be to add a `.catch()` hander to `request` log some additional messages and then rethrow the error but we can't specially address CORS so the best case message would be something like

```
ArcGIS REST JS: A Network error occurred. This commonly occurs because:

• You do not have a network connection. Please confirm that you are connected to the internet.
• The URL you requested could not be found. Please confirm that you entered the correct URL.
• The instance of ArcGIS Server or ArcGIS Portal does not have CORS enabled. Either enable CORS or make sure this domain is whitelisted for CORS access
```

**Comment by patrickarlt** [comment] 2022-03-14 22:03
I'm going to close this. I don't think we need additional documentation on this. It is also going to be tricky to determine what is a network error so we can't really do much about this.

**Closed by patrickarlt** 2022-03-14 22:03 UTC
