### ISSUE TITLE
 Allow for "unmanaged" UserSessions where tokens are not checked for expiration

### ISSUE THREAD

**Issue by sandromartis** [Esri/arcgis-rest-js#667] opened 2020-03-05 15:43 UTC
The `authentication` prop is required in both `IAddItemDataOptions` and `IUpdateItemOptions` which means that a `UserSession` has to be passed in.

This is not ideal in a server-side environment where only a token is available but not a `UserSession`.
Would it be possible to change those two types so that `authentication` is optional and instead a token can be passed in through `params`?

In `applyEdits` for example, `authentication` is also not required and a token can be passed through directly via:

```
params: {
  token: 'token'
}
```

There it seems to be handled just fine. Maybe we could change `addItemData` and `updateItem` to be similar?

Let me know if I should make a PR.

**Comment by jgravois** [comment] 2020-03-05 21:50
hey @sandromartis :wave:

> not ideal in a server-side environment where only a token is available but not a `UserSession`.

very little beyond a token is need to instantiate a `UserSession`.

```ts
const session = new UserSession({
  clientId, // comes from registering an application for OAuth 2.0
  token,
  tokenExpires
});
// ref: /packages/arcgis-rest-auth/test/UserSession.test.ts#L51-L55
```

the demo application below is an example of how server-side code can use OAuth 2.0 to help folks sign in and create a UserSession that is shared by both the client and server.

[/demos/webmap-checker-sapper](https://github.com/Esri/arcgis-rest-js/tree/master/demos/webmap-checker-sapper)

**Comment by sandromartis** [comment] 2020-03-06 10:18
hey @jgravois 😉 

I actually tried creating the `UserSession` on-the-fly but I ran into `ArcGISAuthError: Unable to refresh token.` errors.

In your example, what should `tokenExpires` be?

Our use case is a little bit different than a traditional client/server application.
We are building a serverless (and thus completely stateless) GraphQL API. The goal is that our API users pass in an ArcgisOnline token when making requests and that token gets directly forwarded to the AGO Rest API (through arcgis-rest-js).
If a token is expired the Rest API would throw an error which then gets returned to our GraphQL API user. So it's the responsibility of the user to have an updated token, same as if they would use the Rest API directly. Does that make sense?

This works nicely with just using
```
params: {
  token: 'token'
}
```

but gets a bit more tricky with a `UserSession` because it tries to refresh the token if it's expired.
It looks like I can just set `tokenExpires` to some date in the future, but it seems like a bit of a hacky workaround.

**Comment by jgravois** [comment] 2020-03-06 15:05
> Does that make sense?

not really, but don't fret. if you're trying to ignore the authentication helpers this library provides and do it yourself for 'reasons', you are never alone. plenty of other developers have expressed a similar desire and I'm positive gobs more are just doing it without telling us.

> Let me know if I should make a PR.

I no longer work @Esri and as such I no longer actually maintain `rest-js`, but in my own humble opinion, I'm fine with a PR that makes authentication optional in `IUserOptions` as long as it doesn't break any tests.

there's something to be said for just 'getting out of the way' sometimes.

https://github.com/Esri/arcgis-rest-js/blob/7da704ccb6dacace058a64935cf4e5690181df12/packages/arcgis-rest-auth/src/authenticated-request-options.ts#L19-L24

beware though, many moons ago I was the one that wrote that interface to begin with. I don't remember being overly jazzed to enforce rules and regulations on consumers of the lib. IIRC, it was purely to appease the TS gods and carry on with the item ownership checking we do under the hood.

example here: https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-portal/src/items/helpers.ts#L232

I have no doubt that anyone that the goal is attainable to someone that knows more about TypeScript than I did then (it wasn't much), but you still may have your work cut out for you. 🤞

**Comment by jf990** [comment] 2020-03-06 23:48
I'm curious, does application authentication not apply in this case? This is exactly the scenario for app auth. Should we allow it here? I'm not knowledge enough of the portal use case here, is there the ability to create an app and get the client id/secret?

this change would still be required.

```typescript
export interface IUserRequestOptions extends IRequestOptions {
    authentication: UserSession | ApplicationSession;
}
```

**Comment by jgravois** [comment] 2020-03-07 02:44
> does application authentication not apply in this case?

it does not. whether the code is running on the client or server, "Applications cannot create, update, share, modify, or delete items (layers, files, services, maps) in ArcGIS Online or ArcGIS Enterprise."

https://developers.arcgis.com/documentation/core-concepts/security-and-authentication/limitations-of-application-authentication/

**Comment by jf990** [comment] 2020-03-07 16:16
@jgravois thanks for clearing that up for me, it makes total sense.

**Comment by tomwayson** [comment] 2020-03-12 21:16
I'd be more interested in seeing a new class like `TokenSession` that implements `IAuthenticationManager` that is designed for this purpose.

**Comment by jf990** [comment] 2020-03-12 22:35
I was thinking more about this issue and wanted to propose an idea similar to @tomwayson. we should think about how the API is intended to work and design patterns that work with the model and not against it. It doesn't make sense to me to promote a programming pattern to override an intended purpose, in this case session management derived from `IAuthenticationManager ` and ask users to stuff params to override it when what we intended doesn't work.

I was going to propose an unmanaged `UserSession` and `ApplicationSession`. The user could set their own token (and probably expire time) and doing so put the session in the unmanaged state such that the internal code would not manage the token and return the error code 403/498/499 and the user is responsible for dealing with it, refreshing the token, updating the session and retrying. Doing it this way means all our documentation and samples and architecture work exactly as intended and there are no workarounds and we and users don't have to maintain fragile code.

Doing this with a separate `TokenSession` class is effectively the same idea and better for encapsulating the functionality within its own class and interface. It has a different impact on the existing code base and documentation.

I'm not sure who to run this by, is there a design council for this project?

**Comment by tomwayson** [comment] 2020-03-12 22:42
No design council per say, but I think if @sandromartis can verify that what we're proposing would work for him and if @patrickarlt could weigh in, well I'd consider that a quorum.

**Comment by patrickarlt** [comment] 2020-03-12 23:44
> Our use case is a little bit different than a traditional client/server application.
>
> We are building a serverless (and thus completely stateless) GraphQL API. The goal is that our API users pass in an ArcgisOnline token when making requests and that token gets directly forwarded to the AGO Rest API (through arcgis-rest-js).
>
> If a token is expired the Rest API would throw an error which then gets returned to our GraphQL API user. So it's the responsibility of the user to have an updated token, same as if they would use the Rest API directly. Does that make sense?

@sandromartis this all makes sense. I think this is a use case we should support. You see the `ArcGISAuthError: Unable to refresh token.` errors because the API trys to manage token refreshing similar to how the JS API does. In order to avoid this error you need to initalize `UserSession` with either `clientId` and `refreshToken` (server side oAuth) or `username` and `password` (pre-oauth "generate token" workflow). In situations where we cannot refresh we expect the application to manage it and "retry" the request.

I think manually creating a `UserSession` should work if you set a `tokenExpires` far in the future would work for the short term. 

In your case you expect end users to mange the `token` themselves which is fine. I think I would prefer to handle this like so (these are in order of my preference 1 being highest):

1. Do as @jf990 suggested in and create a new class I would suggest just `Token`:

    ```js
    import { Token } from "@esri/arcgis-rest-auth";
    import { updateItem } from "@esri/arcgis-rest-portal";

    updateItem({
      item: {
        id: "3ef",
        description: "A three hour tour"
      },
      authentication: new Token("...")
    })
    ```
3. This would mean the signature for `authentication` is now:
    ```ts
    UserSession | ApplicationSession | Token
    ```

Alternately if we don't want to add a new class we could do the following I think we should just assume the token is valid:

```js
import { UserSession } from "@esri/arcgis-rest-auth";
import { updateItem } from "@esri/arcgis-rest-portal";

updateItem({
  item: {
    id: "3ef",
    description: "A three hour tour"
  },
  authentication: new UserSession({
    token: "YOUR_TOKEN" // just assume this isn't expired...
  })
})
```

The final option would be to make `authentication` optional throughout the whole API. The reason it is optional for `applyEdits` is because public layers don't require auth so we mark that property as optional. This is my least favorite option since TypeScript will no longer  warn users when they call a method where auth is required with no auth..

**Comment by sandromartis** [comment] 2020-03-13 10:31
Thanks everybody for weighing on this. The proposed solutions all sound good to me and should cover our use case. I'm not super familiar with the codebase so I can't say which solution would make more sense.

The only issue I see is what @jgravois mentioned. Currently the `updateItem` function calls `determineOwner` which itself, as a last resort, uses the `username` from the `UserSession`.

 So I guess `authentication: new Token("...")` wouldn't work unless we find some other solution for that.

Passing some kind of unmanaged `UserSession`
```
  authentication: new UserSession({
    username: "jsmith",
    token: "YOUR_TOKEN" // just assume this isn't expired...
  })
```
could work I guess.

**Comment by patrickarlt** [comment] 2020-03-16 16:38
The more I think about this the more I like just allowing `token` without any other properties.

```js
import { UserSession } from "@esri/arcgis-rest-auth";
import { updateItem } from "@esri/arcgis-rest-portal";

updateItem({
  item: {
    id: "3ef...",
    description: "A three hour tour"
  },
  authentication: new UserSession({
    token: "YOUR_TOKEN" // just assume this isn't expired...
  })
})
```

It would be pretty simple to add a case for this. I think we need to make `determineOwner` fetch the `username` from the portal if it is undefined. or possibly add a function to `UserSession` to fetch the username and cache it since the `username` for a given `token` will never change. I'll make a separate issue for this.

Assigning this to myself.

**Comment by tomwayson** [comment] 2021-06-10 05:40
In a call today, @patrickarlt suggested that we should instead have `IRequestOptions` have `authentication: IAuthenticationManager | string`, and w/in `request()`, we'd check to see if `typeof authentication === 'string'` and if so we just assume you know what you're doing and we assume it's a valid token.

**Comment by patrickarlt** [comment] 2022-03-14 15:48
I'm closing this. In 4.0 you can pass the string token directly to `authentication`. There is a warning about this because it lacks the error handling and you really should use the new `fromToken()` static method.

**Closed by patrickarlt** 2022-03-14 15:48 UTC
Labels: enhancement
